services:
  lovebox-telegram-sender:
    image: ${LOVEBOX_TELEGRAM_SENDER_IMAGE:-patertuck/lovebox-telegram-sender:main}
    container_name: lovebox-telegram-sender
    env_file:
      - ./.env
    environment:
      INTEGRATION_MESSAGES_DB_PATH: /app/data/messages.db
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
