# Infrastructure Settings
spring.threads.virtual.enabled=true

# Application Settings
lovebox.enabled=${LOVEBOX_ENABLED:true}
logging.level.com.patbaumgartner=debug
logging.level.org.telegram.telegrambots=info

# Lovebox Login
lovebox.email=${LOVEBOX_EMAIL:}
lovebox.password=${LOVEBOX_PASSWORD:}

# Lovebox Setting
lovebox.signature=${LOVEBOX_SIGNATURE:}
lovebox.device-id=${LOVEBOX_DEVICE_ID:}
lovebox.box-id=${LOVEBOX_BOX_ID:}

# Telegram Bot Settings
bot.username=${BOT_USERNAME:}
bot.token=${BOT_TOKEN:}
bot.allowed-chat-id=${BOT_ALLOWED_CHAT_ID:}

# Scheduler Integration
integration.scheduler-token=${INTEGRATION_SCHEDULER_TOKEN:}
integration.messages-db-path=${INTEGRATION_MESSAGES_DB_PATH:data/messages.db}
