# Infrastructure Settings
spring.threads.virtual.enabled=true
spring.main.keep-alive=true

# Application Settings
lovebox.enabled=${LOVEBOX_ENABLED:true}
logging.level.com.patbaumgartner=debug
logging.level.org.telegram.telegrambots=info

# Lovebox Login
lovebox.email=${LOVEBOX_EMAIL:}
lovebox.password=${LOVEBOX_PASSWORD:}

# Lovebox Setting
lovebox.signature=${LOVEBOX_SIGNATURE:}
lovebox.device-id=${LOVEBOX_DEVICE_ID:}
lovebox.box-id=${LOVEBOX_BOX_ID:}

# Telegram Bot Settings
bot.username=${BOT_USERNAME:}
bot.token=${BOT_TOKEN:}
bot.allowed-chat-id=${BOT_ALLOWED_CHAT_ID:}

# Scheduled messages
messages.database-path=${MESSAGES_DATABASE_PATH:data/messages.db}
messages.document-path=${MESSAGES_DOCUMENT_PATH:message.docx}
messages.pictures-path=${MESSAGES_PICTURES_PATH:}
